# configs/config.yaml
# 1-depth 섹션만 사용 (nested 최소)

model:
  name_or_path: "unsloth/gemma-3-27b-it-unsloth-bnb-4bit"
  use_unsloth: true
  load_in_4bit: true

tokenizer:
  max_seq_length: 10000
  padding_side: "right"

train:
  train_path: "/data/ephemeral/home/ksat_data/augments.csv"
  valid_path: "/data/ephemeral/home/ksat_data/valid.csv"
  output_dir: "./outputs_augments"

  # load adapter
  load_adapter: true
  adapter_path: "./outputs_train/final_adapter"

  # LoRA (train only)
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "v_proj"]

  # trainer
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5e-6
  lr_scheduler_type: "cosine"
  num_train_epochs: 5

  fp16: true
  gradient_checkpointing: false
  seed: 42
  weight_decay: 0.01
  report_to: "wandb"  # none | wandb | tensorboard

infer:
  # test_path: "/data/ephemeral/home/ksat_data/test.csv"
  test_path: "/data/ephemeral/home/yejoon/pro-nlp-generationfornlp-nlp-15/augments.csv"
  output_path: "pred_gemma.csv"

  # adapter_path가 null이면 {train.output_dir}/final_adapter 사용 (코드에서)
  use_adapter: true
  adapter_path: null

wandb:
  project: "koreasat_yejoon"
  entity: "hakiful-ai"
  name: "unsloth/gemma-3-27b-it-unsloth-bnb-4bit_aug"