# configs/config.yaml
# 1-depth 섹션만 사용 (nested 최소)

model:
  name_or_path: "beomi/gemma-ko-2b"

tokenizer:
  max_seq_length: 2048
  padding_side: "right"

train:
  train_path: "/data/ephemeral/home/data/train.csv"
  # eval path가 없다면 train data split, 있다면 split 하지 않음.
  # eval_path: "/data/ephemeral/home/data/valid.csv"
  output_dir: "./outputs"

  # LoRA (train only)
  lora_r: 6
  lora_alpha: 8
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "v_proj"]

  # trainer
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 2.0e-5
  lr_scheduler_type: "cosine"
  num_train_epochs: 1

  fp16: true
  gradient_checkpointing: "unsloth" # true | false | "unsloth"
  seed: 42
  weight_decay: 0.01
  report_to: "wandb"  # none | wandb | tensorboard

  use_unsloth: true

infer:
  test_path: "/data/ephemeral/home/data/test.csv"
  output_path: "output.csv"

  # adapter_path가 null이면 {train.output_dir}/final_adapter 사용 (코드에서)
  # adapter_path에 artifact 주소가 있을 경우, 클라우드에 저장된 모델 사용
  use_adapter: true
  adapter_path: null

wandb:
  project: "koreasat_woohyun"
  entity: "hakiful-ai"
  name: "beomi/gemma-ko-2b-joonbaseline-fix_v2"