# configs/config.yaml
# 1-depth 섹션만 사용 (nested 최소)

model:
  # name_or_path: "beomi/gemma-ko-2b"
  name_or_path: "unsloth/gemma-3-27b-it-bnb-4bit"
  load_in_4bit: true

tokenizer:
  max_seq_length: 4096
  padding_side: "right"

train:
  train_path: "/data/ephemeral/home/ksat_data/splitted/train.csv"
  eval_path: "/data/ephemeral/home/ksat_data/splitted/valid.csv"
  output_dir: "./outputs_gemma"

  # LoRA (train only)
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  use_rslora: true
  use_dora: true
  neftune_noise_alpha: 5

  # trainer
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 1e-5
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  num_train_epochs: 5

  fp16: true
  gradient_checkpointing: "unsloth"
  seed: 42
  weight_decay: 0.01
  report_to: "wandb"  # none | wandb | tensorboard

infer:
  test_path: "/data/ephemeral/home/ksat_data/test.csv"
  output_path: "batch_4_lr_5e-6_loradrop_0.05.csv"

  # adapter_path가 null이면 {train.output_dir}/final_adapter 사용 (코드에서)
  use_adapter: false
  adapter_path: null
  
  inference_method: "logits"
  max_new_tokens: 4096

wandb:
  project: "koreasat_woohyun"
  entity: "hakiful-ai"
  name: "unsloth/gemma-3-27b-it-bnb-4bit_batch_16_lr_1e-5_loradrop_0.05_train"
  group: "unsloth/gemma-3-27b-it-bnb-4bit"
  job_type: "train"
  notes: "batch_16_lr_1e-5_loradrop_0.05"